BOM update for views-with-compose
google-developer-training/basic-android-kotlin-compose-training-juice-tracker pull request #6
Opened 2023-02-03 22:52 UTC by sc-gds-lxl

2023-02-03 22:57 UTC, osuleymanova approved these changes

2023-02-06 19:38 UTC, yenerm requested changes

2023-02-06 19:38 UTC, yenerm commented on build.gradle
>          room_version = '2.4.3'
2.5.0

2023-02-07 20:49 UTC, yenerm approved these changes

2023-02-07 21:56 UTC, merged